package com.github.catatafishen.agentbridge.agent.claude;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests for {@link InstructionsManager} pure static methods.
 * <p>
 * Platform-dependent method {@link InstructionsManager#ensureInstructions} is not tested here
 * because it requires {@link com.intellij.openapi.project.Project} and {@link AgentProfile}
 * which depend on the IntelliJ platform. Integration tests for ensureInstructions with
 * mocked platform classes should be added in a platform-aware test suite if needed.
 */
class InstructionsManagerTest {

    private static final String SENTINEL = InstructionsManager.INSTRUCTIONS_SENTINEL;

    // ── spliceInPlace: basic cases ──────────────────────────────────────────

    @Test
    void spliceInPlace_replacesBlockBetweenStartAndEndMarkers() {
        String existing = ""
            + "---\n"
            + SENTINEL + "\n"
            + "OLD BLOCK\n"
            + "> End of auto-generated instructions\n"
            + "---\n"
            + "User content";
        String newBlock = SENTINEL + "\n\nNEW INSTRUCTIONS\n\n> End of auto-generated instructions\n---";

        String result = InstructionsManager.spliceInPlace(existing, newBlock);

        assertNotNull(result);
        assertFalse(result.contains("OLD BLOCK"));
        assertTrue(result.contains("User content"));
        assertTrue(result.contains("NEW INSTRUCTIONS"));
    }

    @Test
    void spliceInPlace_returnsNullWhenNoBlockFound() {
        String existing = "Just user content with no sentinel.";
        String newBlock = SENTINEL + "\n\nNEW\n\n> End of auto-generated instructions\n---";

        assertNull(InstructionsManager.spliceInPlace(existing, newBlock));
    }

    @Test
    void spliceInPlace_exactMatchReturnsSame() {
        String existing = ""
            + "---\n"
            + SENTINEL + "\n\n"
            + "CONTENT\n\n"
            + "> End of auto-generated instructions\n"
            + "---\n";
        String newBlock = SENTINEL + "\n\nCONTENT\n\n> End of auto-generated instructions\n---";

        String result = InstructionsManager.spliceInPlace(existing, newBlock);
        assertNotNull(result);
        // Substring after markers should be identical
        assertTrue(result.contains("CONTENT"));
    }

    @Test
    void spliceInPlace_replacesLegacySentinel() {
        String existing = ""
            + "---\n"
            + "> ⚙️ Auto-generated by IDE Agent for Copilot — do not edit this section\n\n"
            + "LEGACY CONTENT\n\n"
            + "> End of auto-generated instructions\n"
            + "---\n"
            + "User content";
        String newBlock = SENTINEL + "\n\nNEW CONTENT\n\n> End of auto-generated instructions\n---";

        String result = InstructionsManager.spliceInPlace(existing, newBlock);

        assertNotNull(result);
        assertFalse(result.contains("LEGACY CONTENT"));
        assertTrue(result.contains("NEW CONTENT"));
        assertTrue(result.contains("User content"));
    }

    // ── edge cases ─────────────────────────────────────────────────────────

    @Test
    void spliceInPlace_handlesNullExisting() {
        assertNull(InstructionsManager.spliceInPlace(null, "block"));
    }

    @Test
    void spliceInPlace_handlesNullNewBlock() {
        assertNull(InstructionsManager.spliceInPlace("existing content", null));
    }

    @Test
    void spliceInPlace_handlesEmptyExisting() {
        assertNull(InstructionsManager.spliceInPlace("", SENTINEL + "\n\nblock"));
    }

    @Test
    void spliceInPlace_handlesEmptyNewBlock() {
        String existing = ""
            + "---\n"
            + SENTINEL + "\n"
            + "OLD\n"
            + "> End of auto-generated instructions\n"
            + "---\n";
        // Empty new block — still replaces old with nothing
        assertNotNull(InstructionsManager.spliceInPlace(existing, ""));
    }

    @Test
    void spliceInPlace_handlesCorruptBlockWithNoEndMarker() {
        // Block starts but end marker is missing
        String existing = ""
            + "---\n"
            + SENTINEL + "\n"
            + "BROKEN BLOCK\n"
            + "\n"  // blank line triggers fallback truncation
            + "User content after blank line";
        String newBlock = SENTINEL + "\n\nNEW\n\n> End of auto-generated instructions\n---";

        String result = InstructionsManager.spliceInPlace(existing, newBlock);
        // Should not crash; fallback replaces to blank line
        assertNotNull(result);
        assertTrue(result.contains("NEW"));
        assertTrue(result.contains("User content after blank line"));
    }
}
